name: TimoliaCustom
version: 1.5
author: pizzafreak08
website: http://www.timolia.de/
main: de.dariusmewes.TimoliaCustom.TimoliaCustom
commands:
    checkent:
        usage: /checkent [args]
        description: 
    google:
        usage: /google <msg>
        description: 
    itp:
        usage: /itp [Player] <x> <y> <z>
        description: 
    protnpc:
        usage: /addnpc
        description: 
    sapopvp:
        usage: /sapopvp [gold/eisen/pos1/pos2/warpgold/warpeisen/list]
        description: 
    sgames:
        usage: /sgames
        description: 
    sgcopy:
        usage: /sgcopy <world>
        description: 
    tcustom:
        usage: /tcustom <reload>
        description: 
    west:
        usage: /west help
        description: 