name: TimoliaCustom
version: 1.0
author: pizzafreak08
website: http://www.timolia.de/
main: de.dariusmewes.TimoliaCustom.TimoliaCustom
commands:
    checkent:
        usage: /checkent [args]
        description: Pruefe die Entities auf einem bestimmten Grundstueck
    google:
        usage: /google <msg>
        description: 
    itp:
        usage: /itp [Player] <x> <y> <z>
        description: 
    protnpc:
        usage: /protnpc
        description: Protecte Villager
    sapopvp:
        usage: /sapopvp [gold/eisen/pos1/pos2/warpgold/warpeisen/list]
        description: Befehl fuer die PVP-Arena
    sgames:
        usage: /sgames
        description: Wieviele Tribute leben noch
    sgcopy:
        usage: /sgcopy <map>
        description: Kopiere eine Survival-Games Map
    tcustom:
        usage: /tcustom <reload>
        description: Plugin-Einstellungen
    west:
        usage: /west help
        description: Westliste