name: TimoliaCustom
version: 1.0
author: pizzafreak08
website: http://www.timolia.de/
main: de.timolia.custom.TimoliaCustom
commands:
    checkent:
        usage: /checkent [args]
        description: Pruefe die Entities auf einem bestimmten Grundstueck
    google:
        usage: /google <msg>
        description: goooooooglen
    itp:
        usage: /itp [Player] <x> <y> <z>
        description:
    protnpc:
        usage: /protnpc
        description: Protecte Villager
    rmprot:
        usage: /rmprot
        description: Loescht die LWC-Sicherungen in deiner Selektion
    sapopvp:
        usage: /sapopvp [gold/eisen/pos1/pos2/warpgold/warpeisen/list]
        description: Befehl fuer die PVP-Arena
    sgames:
        usage: /sgames
        description: Wieviele Tribute leben noch
    sgcopy:
        usage: /sgcopy <map>
        description: Kopiere eine Survival-Games Map
    speed:
        usage: /speed [speed]
        description: Stelle deine Fluggeschwindigkeit ein
    tcustom:
        usage: /tcustom <reload>
        description: Plugin-Einstellungen
    tpack:
        usage: /tpack [Spieler] <url>
    west:
        usage: /west help
        description: Westliste