name: TimoliaCustom
version: 1.5
author: pizzafreak08
website: http://www.timolia.de/
main: me.pizzafreak08.TimoliaCustom.TimoliaCustom
commands:
    sapopvp:
        usage: /<command>
    jumper:
        usage: /<command>
    google:
        usage: /<command>
    sgames:
        usage: /<command>
    west:
        usage: /<command>
    tbreload:
    sgcopy:
    tode:
    itp:
    checkent:
    protnpc: